# Generated by Django 5.2.14 on 2026-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
